### ISSUE TITLE
Add support for bootstrap-vue "b-btn"

### ISSUE THREAD

**Issue by simonbrunel** [STUkh/vue-promise-btn#1]
I'm not sure if it's a bug or a feature but it doesn't seem to work correctly when using the `v-promise-btn` directive inside a [`<b-btn>` component](https://bootstrap-vue.js.org/docs/components/button), for example: https://jsfiddle.net/kb728u3j/

```html
<b-btn v-promise-btn @click="submit">Create</b-btn>
```

Currently, nothing happen (the spinner is not displayed - the `hidden` class isn't removed when loading). The same code works as expected with a regular `<button>`.

Versions:
- vue: 2.5.16
- vue-promise-btn: "1.1.0"
- bootstrap-vue: "2.0.0-rc.11"
- Chrome 67.0.3396.99 / Win 10

**Comment by simonbrunel** [comment]
It's caused by the [`b-btn` registering a listener on click](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/button/button.js#L59) so, when [evaluating `handler`](https://github.com/STUkh/vue-promise-btn/blob/master/src/directives/vue-promise-btn.directive.js#L150), `response` is undefined because the [function `invoker` handles multiple functions](https://github.com/vuejs/vue/blob/master/packages/weex-vue-framework/factory.js#L1802) and returns undefined.

Any idea how to workaround that issue without using a `<form>`?

**Comment by STUkh** [comment]
@simonbrunel this issue fixed with v2.0.0, now you can use this plugin with b-btn and other 3rd party plugins in ```extended``` mode.
