### ISSUE TITLE
Calling a function with parameters

### ISSUE THREAD

**Issue by tradingstratagem** [STUkh/vue-promise-btn#2]
I try to pass a parameter for the function called when clicking the button, but I figured out that this doesn't work.
Is it there any workaround in order to pass parameters to the function and still have the spinner working?

`<button class="btn btn-default" @click="test(param1)" v-promise-btn>Save</button>`

Thank you

**Comment by tradingstratagem** [comment]
https://gist.github.com/tradingstratagem/fa6b6af7496867be1b9560e9bc4f487c

**Comment by STUkh** [comment]
@tradingstratagem your app logic a little bit incorrect. Click event should accept function that returns promise, instead of promise instance itself.

**Comment by tradingstratagem** [comment]
The example uses the same mechanism
https://github.com/STUkh/vue-promise-btn/blob/master/example/example.js

**Comment by STUkh** [comment]
@tradingstratagem in your case, function with params should looks like this:
```
function test (param1) {
    // return anonymous function that will be triggered on click from view with "param1" in closure
    return function () {
        return new Promise(function (res, rej) { setTimeout(function () { .res() }, 2000) });
    }
}
```

**Comment by tradingstratagem** [comment]
I tried but nothing happens

**Comment by STUkh** [comment]
@tradingstratagem i've just tested on my own project - all works properly. Close this thread, fell free open new one with jsfiddle or jsbin example if you face this problem again.

**Comment by STUkh** [comment]
@SebastienTainon , @tradingstratagem - you can try v2.0.0 with extended mode - it fixes a lot of issues
