### ISSUE TITLE
Vue 2.6 breaks vue-promise-btn: Error: Please, provide proper handler/action for promise-btn

### ISSUE THREAD

**Issue by GlennMatthys** [STUkh/vue-promise-btn#4]
Running on Vue 2.6, vue-promise-btn errors out on instantiating:

`[Vue warn]: Error in directive promise-btn bind hook: "Error: Please, provide proper handler/action for promise-btn"`

![image](https://user-images.githubusercontent.com/31989842/52281660-dc3a8c80-295e-11e9-99e5-244ffccfe2ac.png)

[Also visible on the website](https://stukh.github.io/vue-promise-btn/).

**Comment by STUkh** [comment]
Thanks for feedback. Will look into in start of the next week.
PR also welcome ;)

**Comment by tradingstratagem** [comment]
Same problem here
